#!/bin/zsh

if [[ "$@" == *"watchman"* ]]; then
    watchman watch-del-all
    watchman shutdown-server
fi

if [[ "$@" == *"clean"* ]]; then
    xattr -w com.apple.xcode.CreatedByBuildSystem true /Users/leogaudin/Documents/Repositories/track-and-trace/application/ios/build
    cd ios
    xcodebuild clean
    cd ../
fi

npx react-native run-ios --device "iPhone" --port 8888
